import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Content Security Policy for VARAI.
 *
 * The pages in `public/` are generated by `design/build.py` and are fully
 * self-contained: fonts and images are embedded as `data:` URIs, there are no
 * CDN scripts, no external stylesheets and no inline event handlers. That lets
 * us ship a policy with no `script-src 'unsafe-inline'`.
 *
 * Each page does carry one inline <script>. A nonce would mean rewriting the
 * HTML on every request, which we don't want for static files — so instead we
 * hash the inline scripts at startup and allow exactly those hashes. Re-running
 * `npm run design` changes the script, the hash is recomputed on next boot, and
 * the policy stays correct with no manual step.
 */

const INLINE_SCRIPT_RE = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;

/** sha256-base64 of every inline <script> body in the HTML files we serve. */
export function inlineScriptHashes(publicDir: string): string[] {
  const hashes = new Set<string>();

  let files: string[];
  try {
    files = readdirSync(publicDir).filter((f) => f.endsWith('.html'));
  } catch {
    return [];
  }

  for (const file of files) {
    let html: string;
    try {
      html = readFileSync(join(publicDir, file), 'utf8');
    } catch {
      continue;
    }

    for (const match of html.matchAll(INLINE_SCRIPT_RE)) {
      const body = match[1];
      // An empty <script></script> needs no hash.
      if (!body || body.trim() === '') continue;
      // The CSP hash is taken over the exact bytes between the tags.
      hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
    }
  }

  return [...hashes];
}

/**
 * Build the directives object for helmet.
 *
 * `connectSrc` has to allow the API origin. Same-origin covers the normal
 * deployment (Express serves the pages and the API together), but when the
 * frontend is hosted separately — Netlify/Vercel/Pages talking to Render — the
 * browser also needs to be allowed to reach the API host, so anything set in
 * CORS_ORIGIN is added here too.
 */
export function cspDirectives(publicDir: string, corsOrigin: string) {
  const scriptHashes = inlineScriptHashes(publicDir);

  // Allow explicit extra origins to be named for XHR (never '*').
  const extraConnect = corsOrigin
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s !== '' && s !== '*' && /^https?:\/\//.test(s));

  return {
    defaultSrc: ["'self'"],

    // No remote scripts. Only the exact inline blocks we generated.
    scriptSrc: ["'self'", ...scriptHashes],
    scriptSrcAttr: ["'none'"],

    // The design system leans on inline style="" attributes, which hashes
    // cannot cover. Inline styles are a far smaller risk than inline scripts,
    // and no external stylesheet host is permitted.
    styleSrc: ["'self'", "'unsafe-inline'"],

    // Fonts and imagery are embedded in the HTML as data: URIs.
    imgSrc: ["'self'", 'data:'],
    fontSrc: ["'self'", 'data:'],

    connectSrc: ["'self'", ...extraConnect],

    // Nothing here should ever be framed, embedded or navigated away by a form.
    frameSrc: ["'none'"],
    frameAncestors: ["'none'"],
    objectSrc: ["'none'"],
    baseUri: ["'self'"],
    formAction: ["'self'"],
    manifestSrc: ["'self'"],
    workerSrc: ["'self'"],
    upgradeInsecureRequests: [],
  };
}
