/**
 * DEMO MODE — for frontend development before a contract is deployed.
 *
 * ──────────────────────────────────────────────────────────────────────────
 *  A demo verdict is NOT a GenLayer judgment and is never presented as one.
 *    • source            = 'DEMO'
 *    • genlayerTransaction = null   (we do not fabricate hashes)
 *    • validatorResults    = []     (we do not fabricate validator votes)
 *    • consensus           = zeroes (no real votes were cast)
 *  The API additionally returns a top-level `demo: true` and a warning string.
 * ──────────────────────────────────────────────────────────────────────────
 *
 * The decision is derived from simple keyword heuristics so the UI has
 * something plausible to render. It is explicitly NOT AI reasoning.
 */
import type { ContractVerdictPayload, FootballCase, IncidentType } from '../../types/index.js';

const POSITIVE: Record<IncidentType, string> = {
  PENALTY_CLAIM: 'PENALTY',
  FOUL_CLAIM: 'FOUL',
  CARD_DECISION: 'RED_CARD',
  HANDBALL_CLAIM: 'HANDBALL',
  GOAL_CLAIM: 'GOAL',
  OFFSIDE_CLAIM: 'OFFSIDE',
};

const NEGATIVE: Record<IncidentType, string> = {
  PENALTY_CLAIM: 'NO_PENALTY',
  FOUL_CLAIM: 'NO_FOUL',
  CARD_DECISION: 'YELLOW_CARD',
  HANDBALL_CLAIM: 'NO_HANDBALL',
  GOAL_CLAIM: 'NO_GOAL',
  OFFSIDE_CLAIM: 'ONSIDE',
};

const CONTACT_WORDS = ['contact', 'clipped', 'tripped', 'pulled', 'shoved', 'kicked', 'caught', 'stamped'];
const CLEAN_WORDS = ['played the ball', 'won the ball', 'clean', 'no contact', 'minimal', 'dived', 'simulation'];

export function buildDemoVerdict(c: FootballCase): ContractVerdictPayload {
  const text = `${c.description} ${c.refereeCall ?? ''}`.toLowerCase();

  const contact = CONTACT_WORDS.filter((w) => text.includes(w)).length;
  const clean = CLEAN_WORDS.filter((w) => text.includes(w)).length;

  // Not enough to go on → the honest answer, same as the contract would give.
  // (No keyword signal at all means the heuristic has nothing to stand on.)
  if (contact === 0 && clean === 0) {
    return {
      decision: 'INSUFFICIENT_EVIDENCE',
      confidence: 0.3,
      reasoning:
        'DEMO MODE — no GenLayer execution occurred. The submitted description does not establish enough facts to apply a law, so the placeholder returns INSUFFICIENT_EVIDENCE, mirroring how the Intelligent Contract behaves when facts are missing.',
      criteria: {
        location: 'unclear',
        playerContact: 'unclear',
        ballContact: 'unclear',
        challengeIntensity: 'unclear',
        natureOfChallenge: 'unclear',
        evidenceSufficiency: 'insufficient',
      },
      alternativeInterpretation: 'DEMO MODE — not a real analysis.',
    };
  }

  const positive = contact > clean;
  const decision = positive ? POSITIVE[c.incidentType] : NEGATIVE[c.incidentType];
  const margin = Math.abs(contact - clean);
  const confidence = Math.min(0.85, 0.55 + margin * 0.1);

  return {
    decision,
    confidence: Number(confidence.toFixed(2)),
    reasoning:
      `DEMO MODE — this text was generated by a local keyword heuristic, NOT by GenLayer validators. ` +
      `It matched ${contact} contact-indicating term(s) and ${clean} clean-challenge term(s) in the description, ` +
      `and therefore returns "${decision}" as placeholder UI data. Deploy the FootballCourt contract and ` +
      `set VARAI_DEMO_MODE=false to obtain a real decentralized verdict.`,
    criteria: {
      location: c.incidentType === 'PENALTY_CLAIM' ? 'penalty_area' : 'unclear',
      playerContact: contact > 0 ? 'confirmed' : 'unclear',
      ballContact: clean > 0 ? 'confirmed' : 'unclear',
      challengeIntensity: margin >= 2 ? 'high' : margin === 1 ? 'medium' : 'low',
      natureOfChallenge: 'demo heuristic — not analysed',
      // A decided verdict must not simultaneously claim evidence was insufficient.
      evidenceSufficiency: c.evidence.length > 0 ? 'sufficient' : 'partial',
    },
    alternativeInterpretation:
      'DEMO MODE — no alternative interpretation was actually weighed. Real analysis requires GenLayer.',
  };
}

export const DEMO_WARNING =
  'This is a DEMO verdict produced locally for interface development. It was NOT judged by GenLayer validators and has no transaction.';
